import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { OrderList } from "../order-list";
import { listOrders, type SalesOrderSummary } from "@/lib/tenant-sales-api";
vi.mock("@/lib/tenant-sales-api", () => ({ listOrders: vi.fn() }));
vi.mock("next/link", () => ({ default: ({ children, href }: any) => <a href={href}>{children}</a> }));
const item = (id: string, docNo = `SO-${id}`): SalesOrderSummary => ({ id, docNo, status: "COMPLETED", customerName: "Khách", customerPhone: null, itemCount: 1, total: 120000, paymentMethod: "CASH", soldAt: "2026-07-22", createdAt: "2026-07-22" });
let observerCallback: ((entries: Array<{ isIntersecting: boolean }>) => void) | undefined;
beforeEach(() => { vi.useRealTimers(); vi.mocked(listOrders).mockReset(); vi.mocked(listOrders).mockResolvedValue({ items: [item("1")], page: 1, pageSize: 20, total: 1 }); observerCallback = undefined; Object.defineProperty(window, "matchMedia", { configurable: true, writable: true, value: (query: string) => ({ matches: query.includes("max-width") ? false : false, media: query, addEventListener: vi.fn(), removeEventListener: vi.fn() }) }); vi.stubGlobal("IntersectionObserver", class { constructor(cb: typeof observerCallback) { observerCallback = cb; } observe() {} disconnect() {} }); });
describe("OrderList", () => {
it("renders initial loading then canonical rows", async () => { let resolve!: (v: any) => void; vi.mocked(listOrders).mockReturnValueOnce(new Promise(r => { resolve = r; })); render(<OrderList />); expect(screen.getByText("Đơn bán hàng")).toBeInTheDocument(); await act(async () => resolve({ items: [item("1")], page: 1, pageSize: 20, total: 1 })); expect((await screen.findAllByText("SO-1"))[0]).toBeInTheDocument(); });
it("shows empty state", async () => { vi.mocked(listOrders).mockResolvedValueOnce({ items: [], page: 1, pageSize: 20, total: 0 }); render(<OrderList />); expect(await screen.findByText("Không tìm thấy đơn nào")).toBeInTheDocument(); });
it.each([403,404])("shows %s failure and retry", async status => { vi.mocked(listOrders).mockRejectedValueOnce(Object.assign(new Error(),{status})); render(<OrderList/>); expect(await screen.findByRole("alert")).toHaveTextContent(/./); vi.mocked(listOrders).mockResolvedValueOnce({items:[item("retry")],page:1,pageSize:20,total:1}); fireEvent.click(screen.getByRole("button",{name:"Thử lại"})); expect((await screen.findAllByText("SO-retry"))[0]).toBeInTheDocument(); });
it("debounces and ignores stale response", async () => { let old!: (v:any)=>void; vi.mocked(listOrders).mockReturnValueOnce(new Promise(r=>{old=r})); render(<OrderList/>); fireEvent.change(screen.getByRole("searchbox"),{target:{value:"new"}}); await new Promise(r=>setTimeout(r,400)); expect(listOrders).toHaveBeenCalledTimes(2); expect(listOrders).toHaveBeenLastCalledWith(expect.objectContaining({search:"new"})); await act(async()=>old({items:[item("old","STALE")],page:1,pageSize:20,total:1})); expect(screen.queryByText("STALE")).not.toBeInTheDocument(); });
it("replaces rows on desktop pagination", async () => { vi.mocked(listOrders).mockResolvedValueOnce({items:[item("first")],page:1,pageSize:20,total:21}); vi.mocked(listOrders).mockResolvedValueOnce({items:[item("second")],page:2,pageSize:20,total:21}); render(<OrderList/>); expect((await screen.findAllByText("SO-first"))[0]).toBeInTheDocument(); fireEvent.click(screen.getByRole("button",{name:"2"})); expect((await screen.findAllByText("SO-second"))[0]).toBeInTheDocument(); expect(screen.queryByText("SO-first")).not.toBeInTheDocument(); });
it("appends mobile pages with dedupe and terminal state", async () => { Object.defineProperty(window,"matchMedia",{configurable:true,value:()=>({matches:true,addEventListener:vi.fn(),removeEventListener:vi.fn()})}); vi.stubGlobal("IntersectionObserver",class{constructor(public cb:any){} observe(){setTimeout(()=>this.cb([{isIntersecting:true}]),0)} disconnect(){}}); vi.mocked(listOrders).mockResolvedValueOnce({items:[item("a"),item("b")],page:1,pageSize:20,total:3}); vi.mocked(listOrders).mockResolvedValueOnce({items:[item("b"),item("c")],page:2,pageSize:20,total:3}); render(<OrderList/>); expect((await screen.findAllByText("SO-c"))[0]).toBeInTheDocument(); expect(screen.getByText("Đã hiển thị tất cả 3 đơn")).toBeInTheDocument(); });
});
